# Generated by Django 4.2.6 on 2023-11-13 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("anime_id", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("genre", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("episodes", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("members", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "animes", "managed": False,},
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("anime_id", models.IntegerField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "rating", "managed": False,},
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("nome", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "id",
                    models.BigAutoField(
                        default=70000, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfis",},
        ),
    ]
