# Generated by Django 4.2.5 on 2023-09-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_usuarios_usuario"),
    ]

    operations = [
        migrations.RemoveField(model_name="usuario", name="id_usuario",),
        migrations.RemoveField(model_name="usuario", name="idade",),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="sobrenome",
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usuario", name="nome", field=models.TextField(max_length=100),
        ),
    ]
